### PR TITLE
Delegate '@flow' checking to .flowconfig

### PR DESCRIPTION
**Pull request by IgorGee**

### CODE REVIEW

**Comment by krainboltgreene** [comment]
Any chance of this getting in?

**Comment by Arcanemagus** [comment]
Not in it's current state since if that check is removed the code would move on to the check for `.flowconfig`... meaning for _every single_ JS file it would warn about needing a config file.

Also, it seems @IgorGee deleted the repo, so no further work is possible on this so I'm afraid I have to close it.

@krainboltgreene Why are you requesting this anyway? According to https://github.com/AtomLinter/linter-flow/pull/57#issuecomment-196670773 `flow` _requires_ `@flow` to be in the file to check it for types since v0.22, have they changed back on that stance since then?

**Comment by IgorGee** [comment]
Yikes, sorry about that, it seems that I accidentally deleted it when I went on a cleaning spree of my repos.

@Arcanemagus, my intention was to have the option `all=true` for my flowconfig file so that I wouldn't need to put an `@flow` at the top of my files. However, this isn't quite feasible without consequences as I've learned:

My first instinct was to ignore all files in /node_modules/ but that leads to flow errors stating that modules don't exist when I import them.
Not removing /node_modules/ often crashes my computer.

I've yet to find a solution. Putting `@flow` on top of every file in a new project is annoying.

Also, when I tested this change on my local environment, I never got such a warning about needing a config file.

**Comment by Arcanemagus** [comment]
That's because from the sounds of it you already _have_ such a file 😛.

I'm talking about people who work on projects where the majority are _not_ `flow` projects who have this linter enabled. They shouldn't be being spammed to create that file on every single JS project they open, which is what would happen here.

**Comment by krainboltgreene** [comment]
In my case I have files that aren't getting flow checked until I put the `@flow` flag **even though** I have a `.flowconfig` file at the root of the node directory with `all=true`.

**Comment by krainboltgreene** [comment]
In regards to all being supported: It's still on their website and other things seem to recognize it (like the `flow` tool itself)

screen shot 2017-03-20 at 4 03 00 pm

**Comment by Arcanemagus** [comment]
I don't use `flow` myself so all I have to go on is why it was removed in the first place 😛.

**Comment by Arcanemagus** [comment]
I'd be fine with a PR that re-added the old `enableAll` setting, as long as enabling that turned off the prompt to fix a missing configuration file.

**Pull request closed without merging**
