### PR TITLE
WIP: Flow server, missing .flowconfig, auto-install

### PR DESCRIPTION
**Pull request by Adezandee**
This is the continuation fo #33. @steelbrain @nmn

### CODE REVIEW

**Comment by steelbrain** [comment]
@nmn about copying this code to the autocomplete package, I don't think that's a very good idea. I have encountered a similar situation in `atom-hack` and `autocomplete-hack`. I worked around it by creating a generic `exec` function in one, and then exporting it via the services API to the other. It really simplifies the codebases.

**Comment by nmn** [comment]
@steelbrain I agree that common code should be extracted into a helper library. All I was trying to say was that I would love some help from @Adezandee on the autocomplete-flow package as well, as I love the work done here.

**Comment by nmn** [comment]
What my commits add to the PR:
1. devDependencies on eslint and stuff.
2. More flow types. All three files are now type-checked. I had to add a declarations file to make it all work.
3. Reverted to using `check-contents` to re-enable on-the-fly linting.

It all works great locally for me now. @Adezandee If you can go through the changes, we can merge this in and publish it.

Note: The `enableAll` method is now just a flag for whether the linter should check for the `@flow` comment in the file. `check-contents` can be used to check any file anyway, so this should not be a problem.

**Comment by steelbrain** [comment]
@nmn just a side question from my experience with hack, wouldn't it be nice to have an option to switch between project scoped and file scoped linting? In hack, it's very useful, because if I change one shape in one file, it tells me of all the places that are no longer valid by the change.

I have disabled `lintOnFly` in my hack linter because `hh_client` doesn't support stdin, but IMO it was worth getting errors from all the project.

**Comment by nmn** [comment]
@steelbrain I agree that it would be nice to have an option.
I was actually thinking about it myself. wondering if it would be possible to do both `lintOnFly` and full project linting at the same time. So far I think that won't be feasible, but it's certainly a good idea to have an option between the two.

Could something like this actually work:

```
scope: this.onTheFly ? 'file' | 'project',
lintOnFly: !!this.onTheFly,
```

Then with a few conditionals, it could be made to work.

**Comment by nmn** [comment]
@steelbrain I just added another commit that does what you suggested.

1. I changed the scope from `file` to `project`.
2. If the file is unsaved, I use `check-contents` to pass the current buffer as stdin to flow, so linting on the fly continues to work.
3. If the file is saved, and stdin is not needed, I use the normal `check` command to check for errors on the whole project.

Best of both worlds!

**Comment by steelbrain** [comment]
:clap:

**Comment by nmn** [comment]
@Adezandee the ball is back in your court.

**Comment by Adezandee** [comment]
@nmn very nice work, I love it :smile: 
To respond to your earlier comment, I'll surely take a look at your autocomplete-flow package :+1: 
Looks very good to me ! Feel free to merge and publish v4.0.0 probably ?

**Pull request merged**
