### PR TITLE
Respect the value of enableAll

### PR DESCRIPTION
**Pull request by samerbuna**

### CODE REVIEW

**Comment by Arcanemagus** [comment]
That config value doesn't exist, what are you trying to accomplish here?

**Comment by samerbuna** [comment]
In the project README:

## Settings

You can configure linter-flow by editing ~/.atom/config.cson (choose Open Your Config in Atom menu) or in Preferences:

```cson
'linter-flow':
  'executablePath': 'flow'
  'enableAll': false
```

* `executablePath`: Absolute path to the Flow executable on your system.
* `enableAll`: Typecheck all files, not just file containing `@flow`.

**Comment by Arcanemagus** [comment]
Ah, that's a remnant from back when `flow` didn't directly support running on all files, but didn't _prevent_ it, the option was removed when `flow` started only supporting files that included the "enable comment" but apparently taking it out of the readme was missed.

Flow has since changed to again allow linting of any file if configured properly, but this is not the way to handle that. There is an open issue (https://github.com/AtomLinter/linter-flow/issues/146) for this, properly fixing that means finding and parsing the config file here in this package, determining whether that option is enabled and modifying the behavior appropriately. It's not as simple as just "running on all files".

**Comment by Arcanemagus** [comment]
I'm closing this PR, the proper way of handling the desired outcome is an entirely different path that would require rewriting this entire PR anyway.

**Pull request closed without merging**
