### PR TITLE
fix(cwd): use folder containing .flowconfig to run flow

### PR DESCRIPTION
**Pull request by nmn**
Pretty simple fix really.

Switched out `path.dirname(filePath)` for `path.dirname(flowConfig)` and voila, `./node_modules/.bin/flow` now works.

Obviously this comes with the caveat that `.flowconfig` should live in the root of your project folder along with the the node_modules folder. OR you could put the relative path from the .flowconfig to the flow executable.

I think we can automate this in the future. We could look for the node_modules directory automatically, and given an option, use the locally installed version of flow.

NOTE: not sure if the `flow stop` command works correctly for now. Working on that now.

### CODE REVIEW

**Comment by nmn** [comment]
ready for a code review

**Comment by Arcanemagus** [comment]
Btw, `flow-bin` doesn't work on Windows, so automatically finding it like that can't work there.

**Comment by Arcanemagus** [comment]
Would it make sense to just use the root of the project as Atom sees it? That would simplify things somewhat.

**Comment by nmn** [comment]
I considered using the project root as atom sees it. But the flowconfig directory has one less edge-case so I went with that.

Also, even though flow-bin won't work on windows, I don't think that should stop us from trying to use from behind a flag?

(checking why the build failed)

**Comment by Arcanemagus** [comment]
Oh I wasn't saying not to use it where possible, just noting that it's not going to work on Windows :wink:.

The flowconfig directory makes perfect sense :+1:.

**Pull request merged**
